USE [master]
GO

IF EXISTS(SELECT * FROM sys.databases WHERE [name] = 'Kanban')
    DROP DATABASE Kanban
GO

CREATE DATABASE Kanban
GO

USE Kanban
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Tasks(
    Id int IDENTITY(1,1) NOT NULL,
    Title nvarchar(100) NOT NULL,
    AssignedTo int NOT NULL,
    [State] nvarchar(100) NOT NULL,
    CONSTRAINT PK_Tasks PRIMARY KEY CLUSTERED (Id)
)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Tags (
    Id int IDENTITY(1,1) NOT NULL,
    [Name] nvarchar(50) NOT NULL,
    CONSTRAINT PK_Tags PRIMARY KEY CLUSTERED (Id)
)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Users (
    Id int IDENTITY(1,1) NOT NULL,
    [Name] nvarchar(100) NOT NULL,
    Email nvarchar(100) NOT NULL,
    CONSTRAINT PK_Tags PRIMARY KEY CLUSTERED (Id)
)
GO

ALTER TABLE Tasks WITH CHECK ADD CONSTRAINT FK_Tasks_Users FOREIGN KEY(AssignedTo)
REFERENCES Users (Id)
GO
ALTER TABLE Tasks CHECK CONSTRAINT FK_Tasks_Users
GO

ALTER TABLE Tags WITH CHECK ADD CONSTRAINT FK_Tags_Tasks FOREIGN KEY(AssignedTo)
REFERENCES Users (Id)
GO
ALTER TABLE Tasks CHECK CONSTRAINT FK_Tasks_Users
GO